import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { resolve } from "node:path";

export default defineConfig({
  plugins: [react()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        "about-tr": resolve(__dirname, "about-tr.html"),
        "about-en": resolve(__dirname, "about-en.html"),
        "about-de": resolve(__dirname, "about-de.html"),
        "about-ar": resolve(__dirname, "about-ar.html"),
        "team-tr": resolve(__dirname, "team-tr.html"),
        "team-en": resolve(__dirname, "team-en.html"),
        "team-de": resolve(__dirname, "team-de.html"),
        "team-ar": resolve(__dirname, "team-ar.html"),
        "katalog-tr": resolve(__dirname, "katalog-tr.html"),
        "katalog-en": resolve(__dirname, "katalog-en.html"),
        "katalog-de": resolve(__dirname, "katalog-de.html"),
        "katalog-ar": resolve(__dirname, "katalog-ar.html"),
        "kategori-tr": resolve(__dirname, "kategori-tr.html"),
        "kategori-en": resolve(__dirname, "kategori-en.html"),
        "kategori-de": resolve(__dirname, "kategori-de.html"),
        "kategori-ar": resolve(__dirname, "kategori-ar.html"),
        "urun-tr": resolve(__dirname, "urun-tr.html"),
        "urun-en": resolve(__dirname, "urun-en.html"),
        "urun-de": resolve(__dirname, "urun-de.html"),
        "urun-ar": resolve(__dirname, "urun-ar.html"),
        "ihracat-danismanligi-tr": resolve(__dirname, "ihracat-danismanligi-tr.html"),
        "ihracat-danismanligi-en": resolve(__dirname, "ihracat-danismanligi-en.html"),
        "ihracat-danismanligi-de": resolve(__dirname, "ihracat-danismanligi-de.html"),
        "ihracat-danismanligi-ar": resolve(__dirname, "ihracat-danismanligi-ar.html"),
        "projeler-tr": resolve(__dirname, "projeler-tr.html"),
        "projeler-en": resolve(__dirname, "projeler-en.html"),
        "projeler-de": resolve(__dirname, "projeler-de.html"),
        "projeler-ar": resolve(__dirname, "projeler-ar.html"),
        "proje-ahsap-standlar-tr": resolve(__dirname, "proje-ahsap-standlar-tr.html"),
        "proje-ahsap-standlar-en": resolve(__dirname, "proje-ahsap-standlar-en.html"),
        "proje-ahsap-standlar-de": resolve(__dirname, "proje-ahsap-standlar-de.html"),
        "proje-ahsap-standlar-ar": resolve(__dirname, "proje-ahsap-standlar-ar.html"),
        "blog-tr": resolve(__dirname, "blog-tr.html"),
        "blog-en": resolve(__dirname, "blog-en.html"),
        "blog-de": resolve(__dirname, "blog-de.html"),
        "blog-ar": resolve(__dirname, "blog-ar.html"),
        "blogdetay-pleksi-kutu-nasil-uretilir-tr": resolve(__dirname, "blogdetay-pleksi-kutu-nasil-uretilir-tr.html"),
        "blogdetay-pleksi-kutu-nasil-uretilir-en": resolve(__dirname, "blogdetay-pleksi-kutu-nasil-uretilir-en.html"),
        "blogdetay-pleksi-kutu-nasil-uretilir-de": resolve(__dirname, "blogdetay-pleksi-kutu-nasil-uretilir-de.html"),
        "blogdetay-pleksi-kutu-nasil-uretilir-ar": resolve(__dirname, "blogdetay-pleksi-kutu-nasil-uretilir-ar.html"),
        "iletisim-tr": resolve(__dirname, "iletisim-tr.html"),
        "iletisim-en": resolve(__dirname, "iletisim-en.html"),
        "iletisim-de": resolve(__dirname, "iletisim-de.html"),
        "iletisim-ar": resolve(__dirname, "iletisim-ar.html"),
        "gelismeler-tr": resolve(__dirname, "gelismeler-tr.html"),
        "gelismeler-en": resolve(__dirname, "gelismeler-en.html"),
        "gelismeler-de": resolve(__dirname, "gelismeler-de.html"),
        "gelismeler-ar": resolve(__dirname, "gelismeler-ar.html"),
        "kategoriler-tr": resolve(__dirname, "kategoriler-tr.html"),
        "kategoriler-en": resolve(__dirname, "kategoriler-en.html"),
        "kategoriler-de": resolve(__dirname, "kategoriler-de.html"),
        "kategoriler-ar": resolve(__dirname, "kategoriler-ar.html"),
        "kategori-urun-tr": resolve(__dirname, "kategori-urun-tr.html"),
        "kategori-urun-en": resolve(__dirname, "kategori-urun-en.html"),
        "kategori-urun-de": resolve(__dirname, "kategori-urun-de.html"),
        "kategori-urun-ar": resolve(__dirname, "kategori-urun-ar.html"),
        "kvkk-tr": resolve(__dirname, "kvkk-tr.html"),
        "kvkk-en": resolve(__dirname, "kvkk-en.html"),
        "kvkk-de": resolve(__dirname, "kvkk-de.html"),
        "kvkk-ar": resolve(__dirname, "kvkk-ar.html"),
        "cerez-politikasi-tr": resolve(__dirname, "cerez-politikasi-tr.html"),
        "cerez-politikasi-en": resolve(__dirname, "cerez-politikasi-en.html"),
        "cerez-politikasi-de": resolve(__dirname, "cerez-politikasi-de.html"),
        "cerez-politikasi-ar": resolve(__dirname, "cerez-politikasi-ar.html"),
      },
    },
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    globals: true,
  },
});
